version: '2'
services:
  openufp:
    build: /home/container/openufp/
    command: -n -f /blacklist/test -d 3 -F
    volumes:
     - /home/container/openufp/blacklist:/blacklist/test
     - /dev/log:/dev/log
    ports:
     - 4005:4005/tcp
    expose:
     - 4005
    networks:
     - smartfilter
  
  openufp-test:
    build: /home/container/openufp-test/
    command: /openufp-test/openufp-test.py -n -a -u https://www.msn.com -s openufp
    depends_on:
     - openufp
    networks:
     - smartfilter

networks:
  smartfilter:
